[package]
name = "examples-dwm1001-dev"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
avatar-probe-rs = { path = "../avatar-probe-rs" }
vcell = "0.1.2"
nrf52832-hal = "0.8.1"
embedded-hal = "0.2.3"
